### ISSUE TITLE
Spectator see chat via a permission

### ISSUE THREAD

**Issue by porudev** [tomkeuper/BedWars1058#103]
**Is your feature request related to a problem? Please describe.**
Yes you can't see a game's chat for now

**Describe the solution you'd like**
I'd like for normal player to able to see shout and player with permission to see all chat

**Describe alternatives you've considered**
No alternative for now

**Additional context**
None

**Comment by tomkeuper** [comment]
is this implemented?

**Comment by porudev** [comment]
> is this implemented?

no it not, i figure out this should be leave for later on when stuffs is stable

**Comment by tomkeuper** [comment]
You marked it as 'implemented' thats why i was wondering

**Comment by porudev** [comment]
> You marked it as 'implemented' thats why i was wondering

oh my bad sorry
