### ISSUE TITLE
Sword drop Enchant

### ISSUE THREAD

**Issue by Squesly** [tomkeuper/BedWars1058#116]
**Describe the bug**
When you drop stone, iron or diamond sword while u have team upgrade Sharpness
Your will get normal wooden sword that not have sharpness.
It should have Sharpness on Wooden Sword too when drop not only When Respawn

**To Reproduce**
1. Play game
2. Upgrade Sharpness
3. Buy Stone Sword
4. Drop it
5. You get only wooden sword that not have anything enchant on it.

**Comment by ImYenil** [comment]
Fixed https://github.com/tomkeuper/BedWars2023/pull/117

**Comment by tomkeuper** [comment]
Will be fixed with the next release
