### ISSUE TITLE
Sword bug | Chest

### ISSUE THREAD

**Issue by Squesly** [tomkeuper/BedWars1058#119]
**Describe the bug**
Open chest and put wooden sword in chest by use ur mouse click wooden sword in your inventory and move cursor mouse to chest inventory then left click it will close the chest and drop wooden sword but when you pick it up your sword will disappear

**To Reproduce**
1.Put Wooden Sword in chest
2.Pick the wooden sword that got drop after you put it in chest
3.Your sword disappear unless you press E on ur keyboard then right or left click on the first slot (or the slot that u set for being sword)

**Video**
https://streamable.com/dr99lt

**Comment by tomkeuper** [comment]
Will be fixed with the latest patch.
