### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#126]
**Is your feature request related to a problem? Please describe.**
BedWars1058 enjoys a good amount of APIs that make the plugin remarkably customizable with addons, but in some parts of APIs it still lacks

**Describe the solution you'd like**
New APIs for greater customization:

- [x] Shop API (for example ShopManager or ShopIndex API)
- [x] Chat & Economy API (for economy also an event of moneyGain like PlayerXpGainEvent)
- [x] Database API, see #40
- [x] Stats API (Player Stats change event, stats interfaces and methods for creating new custom stats in addons with auto-implement in db)
- [x] Make MoneyGain & XpGain events cancellable
- [x] Upgrades API (like IUpgradesManager or a method to set an upgrade, like sharpened swords, to to a certain or maximum tier)
- [x] BedWars Addon system, see #166

**Comment by tomkeuper** [comment]
for the money api make sure to allow addons to register different economy systems

**Comment by tomkeuper** [comment]
@Xxyuri2005xX Can the Stats API + Moneygain be ticked off?

**Comment by Xxyuri2005xX** [comment]
I'll tick money & xp gain cancellable when pr is done, also is for stat.

**Comment by Xxyuri2005xX** [comment]
I ticked money & xpgain cancellable brc i saw now that you merged that

**Comment by tomkeuper** [comment]
I also made it possible to register custom menus by creating your own menucontent and adding it thru the upgrade manager api. MenuContent also has an interface that can be implemented

**Comment by Xxyuri2005xX** [comment]
ok
