### ISSUE TITLE
Translated messages in chat are based of event player, not recipient player

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#152]
**Describe the bug**
plugin doesnt send message in recipient lang

**Screenshots**
![image](https://github.com/tomkeuper/BedWars2023/assets/29728836/bf69b2fb-96e4-4aa2-82e7-0f5f3749fc10)

**Comment by Xxyuri2005xX** [comment]
this issue happens also on other messages like party ones (languages here: it & en)
![image](https://github.com/tomkeuper/BedWars2023/assets/84080587/ef5059a8-001d-40c4-9e46-761c9a5e9f85)

and with teams display name

**Comment by tomkeuper** [comment]
It seems to happen too all messages, they get sent in the language of the player triggering the action

**Comment by SebastiaanDenHertog** [comment]
Do we wanna show it in the languages that the player has selected so that when I am the player I will see the msg in Dutch because I selected Dutch in my settings?

**Comment by tomkeuper** [comment]
> Do we wanna show it in the languages that the player has selected so that when I am the player I will see the msg in Dutch because I selected Dutch in my settings?

Yes, so target player and not event player

**Comment by tomkeuper** [comment]
Not solved 100% as now the player info is incorrect

**Comment by tomkeuper** [comment]
Issue was solved, caused by different implementation
