### ISSUE TITLE
Suggestion to add group stats

### ISSUE THREAD

**Issue by KKiiya** [tomkeuper/BedWars1058#159]
**Is your feature request related to a problem? Please describe.**
Add group stats to the main bedwars plugin instead of using a addon

**Describe the solution you'd like**
Implementing group stats to bedwars1058

**Describe alternatives you've considered**
Using a addon

**Comment by KKiiya** [comment]
I could do this, i would like to get your thoughts on this

**Comment by Xxyuri2005xX** [comment]
or wait until I would go implements them in 1058 and then we use his commit wanting, at the end he was telling me that they will be in the next update and he will get them done right

**Comment by KKiiya** [comment]
The only problem is, when will be the next update? There is any eta about this?

**Comment by Xxyuri2005xX** [comment]
andrei had planned that 1 feature a day for 30 days and within 1 month there would be, but we don't know if that will be the case, in case in a 10 days we will implement them ourselves

**Comment by KKiiya** [comment]
I see, allright then, i would like to get more thoughts about this to see if everyone agrees or someone gives any suggestion

**Comment by Diamondy01** [comment]
Good idea, but we can always ask the developer of an addon to add support for bedwars2023, more specifically i6y or  Ixf1nity

**Comment by tomkeuper** [comment]
Implemented group stats with PR. Thanks to Agent!

**Comment by tomkeuper** [comment]
Never minndd I didnt say anything
