### ISSUE TITLE
Not Able to Use /bw setMinBuildHeight

### ISSUE THREAD

**Issue by Diamondy01** [tomkeuper/BedWars1058#161]
**Describe the bug**
Not able to set the Minium Height of the Arena via command /bw setMinBuildHeight in SetupArena scenario. I am able to do /bw setMaxBuildHeight Command but not /bw setMinBuildHeight

**To Reproduce**

**Comment by tomkeuper** [comment]
screenshot or console log?

**Comment by Diamondy01** [comment]
It's in the Discord

**Comment by ImYenil** [comment]
![image](https://github.com/tomkeuper/BedWars2023/assets/85287520/246266ea-91d0-4d20-a934-677cda0bfb93)
It work

**Comment by tomkeuper** [comment]
This works for me too
