### ISSUE TITLE
BedWars Addon Improvements

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#166]
**Is your feature request related to a problem? Please describe.**
Actually, when you create an addon for BedWars1058 you need to follow some steps linked inside andrei [wiki](https://wiki.andrei1058.dev/docs/BedWars1058/developers/getting-started)

**Describe the solution you'd like**
An addon class to extend inside your bw addon to register in main plugin class (an addon system like mbedwars one)

**Comment by KKiiya** [comment]
This is already implemented, please take a look at #167 and see if something can be improved or possible errors than can occur when using it

**Comment by tomkeuper** [comment]
This issue is more something we can link the pull to, so it documented somewhere.

**Comment by Xxyuri2005xX** [comment]
> This is already implemented, please take a look at #167 and see if something can be improved or possible errors than can occur when using it

for me your system seems ok, when even tom's requests are resolved we accept and merge

**Comment by porudev** [comment]
Should we close this?
