### ISSUE TITLE
Completely remove respawn screen

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#177]
**Is your feature request related to a problem? Please describe.**
When a player dies they get a quick view of the respawn screen which then dissapears 

**Describe the solution you'd like**
Completely remove the respawn screen. This is mainly for esthatics 

**Describe alternatives you've considered**
Tried to implement this before but main struggles were:

1. Canceling the last damage event and then manually triggering the death event. This is not really an option since we will lose the death cause. causing other components to break. Maybe there will be a work around but from what I've seen so far it will mainly cause problems. Implementation inspired of #144 
```java
public static void checkPlayerHealth(Player p, EntityDamageEvent e, IArena a) {
    e.setCancelled(true);
    Bukkit.getServer().getPluginManager().callEvent(new PlayerDeathEvent(p, Arrays.asList(p.getInventory().getContents()), p.getTotalExperience(), null));
    Bukkit.getServer().getPluginManager().callEvent(new PlayerRespawnEvent(p, a.getReSpawnLocation(), false));
```
This method made the death cause get lost as its not passed to the PlayerDeathEvent which is used in the code.

2. Triggering a respawn event right before the player actually respawns. this will cause the player to appear as respawned making the respawn screen go away as long as its combined with the spigot player respawn. But this add the weird delay which is not caused by the plugin as both commands can be executed at the same exact time and still the delay will happen.
```java
// send respawn packet
Bukkit.getServer().getPluginManager().callEvent(new PlayerRespawnEvent(victim, a.getReSpawnLocation(), false));
Bukkit.getScheduler().runTaskLater(BedWars.plugin, () -> {
    victim.spigot().respawn();
}, 3L);
```

**Comment by Lsy-291** [comment]
look at this
https://github.com/Lsy-291/BedWars1058/commit/72cb1e39a3f0ee1ef6c5a1f5469981b8fef7f73a                                                                                                                                                     https://github.com/Lsy-291/BedWars1058/commit/4c175329ea60c859450bc215dff4f9f87fa3a742

**Comment by tomkeuper** [comment]
Implemented with the latest dev build
