### ISSUE TITLE
Add double/float support for forge upgrades

### ISSUE THREAD

**Issue by AgentNoobff** [tomkeuper/BedWars1058#181]
**Is your feature request related to a problem? Please describe.**
It's extremely inconvenient if we can't use decimals for generator speed.

**Describe the solution you'd like**
Add the possibility to use decimals as delay for forge upgrades.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tomkeuper** [comment]
Already implemented :) Soon it will also be documented
