### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#182]
**Is your feature request related to a problem? Please describe.**
Following the implementation of the various new APIs, bw2023 has achieved a major improvement, but it is not 100% complete

**Describe the solution you'd like**
New API still:
- [x] `IPlayerStats#getCustomStat(String stat)` method.
- [x] `IPlayerStats#saveCustomStat(String stat, int amount)` method.
- [x] Create Column for custom stat.
- [ ] Remove Column for custom stat. (Needed?)
- [ ] New API for handlers (example: handler `bw-team-selector` and opens team selector) mbw inspired
- [ ] API methods for creating your own Lobby/Waiting/Spectator Item

For any other ideas respond with a message in this issue and that idea will be evaluated as well

**Comment by tomkeuper** [comment]
What exactly do you mean with the api handler?

**Comment by Xxyuri2005xX** [comment]
let me give you a practical example. let's take the team selector as an example, instead of making from the addon code a function to be called that gives you the custom item at the moment you enter the arena, you create a waiting item with a handler like "bw-team-selector" and at the click the team selector addon (which owns the handler) does the function of the custom item that you give at the moment of arena join.
the feature is used in mbedwars and is a convenience for addon developers in that they simply create a handler, users add an item waiting with the handler and they are set. it should be noted that in some cases it might be "useless" (like private games, where you have to give the item only with specific conditions) but in many other cases the handler API is potentially useful.

**Comment by tomkeuper** [comment]
I have thought about the api handler with team selector as an example, but you shouldnt have to listen to any join events etc. They can also create an entry in the `pre-game-items` part of the bw2023 config with a command that executes a specific function. This command can be registered using the bw2023 api or it can be a command registered with bukkit directly.

Would this current implementation be sufficient?

**Comment by Xxyuri2005xX** [comment]
if we implement item handler (join, pre-game, spectator) we can on addons like team selector create a simple handler called for example "team-selector" and you put it in bedwars config and when you interact with bedwars waiting item it opens team selector menu.
