### ISSUE TITLE
Bed Destruction cooldown bug

### ISSUE THREAD

**Issue by AgentNoobff** [tomkeuper/BedWars1058#183]
**Describe the bug**
The countdown for bed destruction in the scoreboard is bugged out. The time left is not shown in the desired format and instead is shown in a bugged out red manner.

**To Reproduce**
1. Join any arena and start
2. Wait for bed destruction countdown to start
3. It should be bugged

**Expected behavior**
It should not be bugged and should be shown in the desired manner like the other countdowns.

**Screenshots**
I'll provide screenshots later I'm making the bug report rn cuz ig a lot of people already know abt the bug.

**System (please complete the following information):**
 - OS: Linux
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 23.3

**Additional context**

**Comment by tomkeuper** [comment]
Do you have a screenshot? Im not familiar with this bug

**Comment by AgentNoobff** [comment]
> Do you have a screenshot? Im not familiar with this bug

Sure, here is the screenshot
![Screenshot_20230721-223623~2](https://github.com/tomkeuper/BedWars2023/assets/139374594/ffa33ccf-cd31-4dcd-9aaa-c9a357ec4419)

**Comment by Chromaah** [comment]
i believe this happened to me too, but i just changed it to 'Beds Destroyed in'

**Comment by Diamondy01** [comment]
Average Scoreboard Character Limit Moment

**Comment by tomkeuper** [comment]
yep there is a max amount of characters that can be displayed on the scoreboard. Im afraid this is not something we can fix as its just a minecraft limitation

**Comment by AgentNoobff** [comment]
Ig we should fix the default config for it 🤷‍♂️

**Comment by tomkeuper** [comment]
We can do that tbh
