### ISSUE TITLE
Event call issue

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#186]
**Describe the bug**
When you join an arena as player or spectator the `PlayerJoinArenaEvent` is called after the join message.
To fix this problem is enough moving the `PlayerJoinArenaEvent` call before the join messages inside the methods `addPlayer` & `addSpectator`

**Comment by tomkeuper** [comment]
There doesnt seem to be an issue with this. The events already gets called before the join message. The problem was the implementation. (A method to change the join message has been added but this is unrelated)
