### ISSUE TITLE
Invisibility Potion fix

### ISSUE THREAD

**Issue by AgentNoobff** [tomkeuper/BedWars1058#190]
**Describe the bug**
When invis, other teammates are not able to see their invis teammates. When a player loses his invis, his body isn't visible, only his armor is visible.

**To Reproduce**

**Expected behavior**
Teammates are able to see their invis teammates. Whole player should be visible after losing invis.

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server Software Spigot
 - Server Version 1.8.8
 - Plugin Version 23.3.1-BETA2 (current code compiled)

**Additional context**

**Comment by tomkeuper** [comment]
Can you see if this also happens on the latest dev build? (available in discord or build the development branch)
If so please provide the console log

**Comment by AgentNoobff** [comment]
Why is the development branch actually BedWars2023 and not BedWars1058? 💀

**Comment by AgentNoobff** [comment]
It being BedWars2023 breaks all the addons :/

**Comment by tomkeuper** [comment]
Because master branch is 3 months old and hasnt recieved updates. For us to fix this possible issue we need to know if it happens on BW2023 aswell (the latest version)

**Comment by Xxyuri2005xX** [comment]
> It being BedWars2023 breaks all the addons :/

for addons we are already in the process of resolving by contacting the developers to have support for them implemented.

**Comment by tomkeuper** [comment]
After chatting in discord we found that the only issue was that teammates couldnt see the invis player either, This has now been added.
