### ISSUE TITLE
make bw join random actually random

### ISSUE THREAD

**Issue by Chromaah** [tomkeuper/BedWars1058#194]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when doing a command such as `/bw join random` or `/bw join <group>` and it not taking you to an actual random arena, and instead taking you to the first arena available in alphabetical order.

**Describe the solution you'd like**
- While making sure to maintain the feature of still sending you to an arena with most players, if the arenas are empty/full, it should take you to one of the available arenas RANDOMLY and not in alphabetical order

- If you specify the group with `/bw join <group>` , make it send you to the arena in that group with the most players, and if there is none, then just send to a random arena in that group, again not in alphabetical order.

**Additional context**
This is especially annoying and can be seen when joining a random arena after ending a game, as it will just send you to the same arena over and over and over again unless you choose one.

**Comment by Chromaah** [comment]
plus, if some people dont want this, its always possible to add an option in the config, to change between the original method and the new (how it should be) method.

**Comment by tomkeuper** [comment]
I decided not to add a config option since it should be random and it would not add much at all if we make it configurable
