### ISSUE TITLE
Wooden Sword Issue

### ISSUE THREAD

**Issue by ItzCoolxd** [tomkeuper/BedWars1058#195]
When i get the sword from the chest the wooden sword doesn't disappear like the big network, please fix that and make the sword disappear!

![Screenshot_230](https://github.com/tomkeuper/BedWars2023/assets/143913380/4fa06ff7-1d45-4296-b3f5-6c415b6283ed)

**Comment by KKiiya** [comment]
This seems like it's already in the plugin, just make sure to use the latest build
https://github.com/tomkeuper/BedWars2023/assets/105589176/30f0f38e-4f13-4638-9c0a-c212ba4212b3
