### ISSUE TITLE
Generator Hologram bug chunk

### ISSUE THREAD

**Issue by Squesly** [tomkeuper/BedWars1058#197]
**Describe the bug**
No its a bug

**Explain**
It happens because the hologram generator creates holograms in multiple languages, as you can see. However, when you go near it, it will display only the language you've configured in the config.yml.

https://imgur.com/SAZt8Q8
https://imgur.com/O7RToJ2

**Comment by Chromaah** [comment]
ye that used to happen to me, but since I disabled all other languages, it doesn't anymore

(so i vouch)

**Comment by tomkeuper** [comment]
I've not really found a method to replicate this issue. When does this happen? And can you tell me some server info? (server version etc)

**Comment by KKiiya** [comment]
This has been fixed, please reopen for any further issues
