### ISSUE TITLE
Player invis

### ISSUE THREAD

**Issue by Squesly** [tomkeuper/BedWars1058#199]
https://streamable.com/m8pzq7

You can see armor from far away sometime randomly.
So I think I want when player invis hide armor after drink potion immediately like hypixel
No need to do hideArmor on MoveEvent cause its gonna be like this.

**Comment by tomkeuper** [comment]
Do you have the plugins list? And server version etc.

**Comment by Squesly** [comment]
Server: Paper-1.8.8-445
Java: 17

Plugin list:
![image](https://github.com/tomkeuper/BedWars2023/assets/105538755/1637aa9d-e6e6-4560-9fd2-07b4107526ab)
