### ISSUE TITLE
Add per arena group shops

### ISSUE THREAD

**Issue by ItzCoolxd** [tomkeuper/BedWars1058#200]
1. Make the player in invisible mode when respawning (like hypixel).
2. Add per group shop so we can make a custom shop and upgrades for a specific group instead of making multiple servers. ex: tnt in solos can cost 4 golds and in 3v3 and 4v4 can cost 8 golds (like hypixel).
3. Add per group generator so we can customize the speed of the generator for a specific group.

These were the suggestions i hope you add them in the next update, and thanks for Mr.Caesar and his team for making this wonderful fork of bw1058 it really fixed many bugs!

**Comment by KKiiya** [comment]
1. Could you explain this one a bit more please?
2. Could be an option but that needs to be decided first
3. Thats already a thing

**Comment by ItzCoolxd** [comment]
1. So basically when you die and you enter the respawning mode you aren't invisible like hypixel.
![Screenshot_3](https://github.com/tomkeuper/BedWars2023/assets/143913380/903ceec0-d019-4e5a-841a-8a9e118757bb)
![Screenshot_4](https://github.com/tomkeuper/BedWars2023/assets/143913380/056e7f15-c75b-45ce-90d0-7d5d80a24e44)

**Comment by ItzCoolxd** [comment]
2. I really hope you add that.
3. Oh, is that possible in the generator config?

**Comment by KKiiya** [comment]
I see what you meant in the first one. So the above one is bw2023 and the one below is hypixel right?

**Comment by KKiiya** [comment]
3. Yes, it is a thing via config

**Comment by ItzCoolxd** [comment]
> I see what you meant in the first one. So the above one is bw2023 and the one below is hypixel right?

Yes.

**Comment by ItzCoolxd** [comment]
> 3. Yes, it is a thing via config

Oh cool!
Didn't know that, thanks for letting me know

**Comment by AgentNoobff** [comment]
Hey @tomkeuper check out the 2nd suggestion. It would be awesome if you could implement that :)

**Comment by tomkeuper** [comment]
I understand the need for custom group based shops but without a complete overhaul of the shop system this is not possible. And  since it is possible when using BUNGEE mode as you can create a server for SOLO and a server for DUO etc. I dont think its really worth the hassle of a complete rewrite. 

Btw idk if you looked at the shops.yml config file its already like 1000 lines. If we wanted per group shops it would add quite a lot more

**Comment by AgentNoobff** [comment]
Trust me, it's worth the hassle. Creating a hundred servers for arenas and switching completely to bwproxy will break addons and require tons of more resources.

And about the config, the number of lines doesn't matter as long as it's working and tidy with proper indentation and stuff.

**Comment by Diamondy01** [comment]
I agree with @AgentNoobff

**Comment by tomkeuper** [comment]
I dont really get how it will break addons. Just for some extra servers. And configs that size will never be tidy...

**Comment by Chromaah** [comment]
i think it should be a custom file in a folder, have a main generators folder, and inside have Default shop yml, then let the person create a file named after the group and then boom. done. (ex Solos.yml, will let u use custom shop for the solos group)

not sure if this is easier, or harder, or if even possible. but it would sure be useful for a lot of people, im sure.

**Comment by Chromaah** [comment]
sorry i mean shop folder not generators***

**Comment by ItzSuolis** [comment]
> I understand the need for custom group based shops but without a complete overhaul of the shop system this is not possible. And since it is possible when using BUNGEE mode as you can create a server for SOLO and a server for DUO etc. I dont think its really worth the hassle of a complete rewrite.
> 
> Btw idk if you looked at the shops.yml config file its already like 1000 lines. If we wanted per group shops it would add quite a lot more

You can create multiple shop.yml files like solo_shop.yml , doubles_shop.yml and etc, this will be better
