### ISSUE TITLE
Invis

### ISSUE THREAD

**Issue by ItzSuolis** [tomkeuper/BedWars1058#201]
I can see players when they are invisible when they are far, can you fix that?
![Screenshot_76](https://github.com/tomkeuper/BedWars2023/assets/104707665/e9967309-1fee-49e5-b4ab-bdb1b790711a)

**Comment by Chromaah** [comment]
Tom is already looking for a fix for this.

https://github.com/tomkeuper/BedWars2023/issues/199

**Comment by Squesly** [comment]
Invisibility can't be fixed by code, but it can be addressed by increasing the entity-activate-range (player) in the spigot.yml file to 128. (This have been tested)
