### ISSUE TITLE
API Improvement

### ISSUE THREAD

**Issue by KKiiya** [tomkeuper/BedWars1058#203]
**Is your feature request related to a problem? Please describe.**
Improvement on the ShopBuyEvent event:

Get the item or set the item that is bought as ItemStack (ability to change the item bought, ex: troll gamemode, custom items, ...)

Get the slot that is assigned to the item you bought, set the slot you want to that item in (ex: ability to make hotbar manager addon easier and less buggy)

**Describe the solution you'd like**
Modify the ShopBuyEvent.java class

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AgentNoobff** [comment]
Wow I'd love this

**Comment by tomkeuper** [comment]
@KKiiya were you able to test this and is it sufficient?

**Comment by tomkeuper** [comment]
I assume this is sufficient for now. Please reopen if needed.
