### ISSUE TITLE
Party Bugs

### ISSUE THREAD

**Issue by Chromaah** [tomkeuper/BedWars1058#207]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

When leader of a party leaves the game the party gets disbanded.

### Expected Behaviour

Option 1: Warp the rest of the party to the lobby when leader leaves.

Option 2: When leader leaves the game, prompt to either warp the rest of the party to the lobby or disband the party.

### How to Reproduce

1. Invite players to party
2. Join Game as leader
3. Leave Game as leader

= Party Disbanded

### Additional Info

Your Mom.

**Comment by tomkeuper** [comment]
- [x] Are you sure pop
- [x] If party owner bring party with player
- [x] If not party owner leave party? or just go to lobby

**Comment by tomkeuper** [comment]
Current system work like this:

### If the party owner leaves
Player gets a pop-up 
![image](https://github.com/tomkeuper/BedWars2023/assets/29728836/95ee1270-f34b-4986-ad2b-b92feca90895)

Warp players with arena or not: 
![image](https://github.com/tomkeuper/BedWars2023/assets/29728836/b74a0149-ef0c-44bf-8a9a-d2d204971481)
![image](https://github.com/tomkeuper/BedWars2023/assets/29728836/b800a59f-8a78-4bb3-99d0-f691a488688e)

### If party member leaves
Instant warp to lobby but player doesnt leave the party. 
Player will be warped to new game when party owner joins it

**Comment by tomkeuper** [comment]
Has support for all languages btw!
