### ISSUE TITLE
Endstone can be broken with fireball

### ISSUE THREAD

**Issue by Chromaah** [tomkeuper/BedWars1058#212]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

Fireballs can damage and break endstone. For example, let's say that I built an Endstone and Wool bed defense. You could simply throw one fireball, and would have access to break the bed. This would make pickaxes useless and the game overall kinda boring and easy.

### Expected Behaviour

The endstone should not break when a fireball hits it, only if it's TNT.

### How to Reproduce

1. Buy a fireball from the shop
2. Aim at endstone (more specifically an endstone bed defense maybe)
3. Throw the fireball"

= Endstone Destroyed

**Comment by tomkeuper** [comment]
Should be implemented now!
