### ISSUE TITLE
Vanilla drop not working

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#214]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

vanilla drop isn't working and drop are on the spec location 
maybe vanilla drop come too late ?

If respawnfixer is built in bw2023 its maybe the problem , because i found some issues with vanilla drop on bw1058 with this addon , but if i remove it , there is no problem.

### Expected Behaviour

vanilla drops

### How to Reproduce

1. activate vanilladrop on the arena.yml
2. kill a player
3. stuff droping at the spectator location

### Console Log

https://pastebin.com/q809Zia7

### Additional Info

https://youtu.be/ihuCH-qTrR8

**Comment by tomkeuper** [comment]
Can you test if it works properly with the latest build in discord?

**Comment by tomkeuper** [comment]
Ill close this for now. Let me know if it doesnt work still
