### ISSUE TITLE
Shift click sword bug!

### ISSUE THREAD

**Issue by SunshroomChan** [tomkeuper/BedWars1058#220]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

After you fixed sword bug Chest/Ender Chest so plugin got another error that would be critical on shop when you shift clicking on sword only!

### Expected Behaviour

No

### How to Reproduce

1. Go on a random arena
2. Open shop menu
3. Press shift click on a sword and then you get it for free!

### Console Log

No error on here

### Errors

No error on here

### Additional Info

Video: https://drive.google.com/file/d/12zTlqS7ZcyMw3ggpQ-kIIB7u4xBxzgSf/view

**Comment by tomkeuper** [comment]
Should be fixed in the latest dev build. Please let me know your findings;

**Comment by SunshroomChan** [comment]
> Should be fixed in the latest dev build. Please let me know your findings;

The bug was fixed, thanks!

**Comment by SunshroomChan** [comment]
@tomkeuper as i mentioned so the shift clicking sword bug is happened again on Bedwars Compass addon when it's menu can shift clicking too!

**Comment by tomkeuper** [comment]
What do you mean with it happening again with the BedWars Compass addon? Since that sounds like an issue with the addon

**Comment by SunshroomChan** [comment]
> What do you mean with it happening again with the BedWars Compass addon? Since that sounds like an issue with the addon

The code about sword handler has shift clicking on it, if you have Wooden Sword and shift clicking on a Iron Sword that has in Compass Addon menu, maybe some other plugin that has chest menu (mostly Bedwars2023's addon) from other plugin could cause this bug if player using shift clicking that has from stone sword and greeter, so the item of Iron Sword that appeared on Compass Addon has replace Wooden Sword as that slot has it in start of the game, the same issue that i reported it before on Shop

**Comment by tomkeuper** [comment]
Any chance you can record this again? The original video is gone and I am not 100% sure what you mean

**Comment by tomkeuper** [comment]
bump

**Comment by tomkeuper** [comment]
This issue is closed due to being stale. You can reopen this if needed or create a new issue.
