### ISSUE TITLE
Implement new upgrade

### ISSUE THREAD

**Issue by ManiXD** [tomkeuper/BedWars1058#227]
Implement some new upgrades for team upgrade which is choosable, if users want it to be enabled or not like feather falling or other things.

**Comment by tomkeuper** [comment]
Have you tried changing the config? :D
(I am quite sure you can just add more/other effects by adding them into the config)

**Comment by tomkeuper** [comment]
This issue is closed due to being stale. You can reopen this if needed or create a new issue.
