### ISSUE TITLE
Shrinking Border Event ?

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#229]
hello , can you add a option to have Shrinking Border Event to just have the middle map at the end of a bw game ?
like this 
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/d1530d7d-1590-48fa-8c5b-d8375e167bab)

**Comment by tomkeuper** [comment]
I think this should be done using an addon. If changes are required within bw2023 I am more than welcome to cooperate but the functionality should come from an addon. I do like the idea tho!
