### ISSUE TITLE
BW2023 MariaDB Global Recode

### ISSUE THREAD

**Issue by ushereats** [tomkeuper/BedWars1058#231]
We need to globally recode the 'bedwars2023' database. Instead of querying to save data every second, it's more efficient to store it in memory and then save it. Currently, the system queries per stat change, but it's more efficient to save data in memory and then query to save it after the game ends.

**Comment by tomkeuper** [comment]
Player stats are not saved per stat change. Its only saved when a player leaves the arena. (At the end of a game or when they leave during the game)

Not sure why it was assumed to be done every time a stat is changed
