### ISSUE TITLE
Some party bug 

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#232]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

1) When i join with my friend , it won't start the game on 1v1 arena
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/53a7cace-ecf8-41d4-8c22-b453ebedec29)

2) When i want to leave the waiting game , it ask to me if i want to summon party with you , if i press yes , it don't tp party with me on the lobby,  and if i join another waiting game , it won't warp the party to me on the waiting game.

3) If my party leave the waiting lobby or in-game arena , it will make him leave the party automatically.

4) And the /disband command throw an error in the console
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/30caa349-fb83-49ba-8345-4c099e808b5a)

Here is a video

https://youtu.be/2OEIOYvkBco

### Expected Behaviour

1) The game should start 

2) Players should be summoned on the lobby with me if i choose yes 

3) It should not make players leave the party automatically

4) Seem to not be a big problem because the party is correctly disbanded as i can see but should not throw error in console

### How to Reproduce

do what i do on the video

### Console Log

https://pastebin.com/ZmVm00fH

### Errors

https://pastebin.com/ZmVm00fH             check last lines

### Additional Info

1.8.8 paper , java17 , windows10

**Comment by tomkeuper** [comment]
Both issues should be fixed. You will be able to download them when a new release is made!

**Comment by tomkeuper** [comment]
Just FYI. Its normal behaviour if you are in a party, the arena wont start if you are the only people in the game. If a third player joins it will start

**Comment by AIGLE25** [comment]
> Just FYI. Its normal behaviour if you are in a party, the arena wont start if you are the only people in the game. If a third player joins it will start

How a third player can join if there is only 2 player max on the arena ?
