### ISSUE TITLE
Be invisible in the lobby + allow placing blocks in the lobby + still being in a game while being in the lobby

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#246]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

I can place blocks on the lobby while being invisible and in a game 

### Expected Behaviour

I must still be in the party , and not able to be in the game while being in lobby and able to place blocks

### How to Reproduce
join a game , /leave , /rejoin , /leave and you are invisible + still in the game while being in the lobby + you can place blocks in the lobby

(EDIT) No need to be in a party , but i shouldn't leave the party on /leave

### Console Log

https://pastebin.com/Lk4zy82Z

### Errors

https://pastebin.com/Lk4zy82Z

### Additional Info

https://www.youtube.com/watch?v=QsOEECX-YBo

**Comment by tomkeuper** [comment]
Leave logic after rejoining has been changed to fix this issue
