### ISSUE TITLE
New version of bw2023 is incompatible with NewAmazingLuckyblocks

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#247]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Plugin/Server Incompatibility

### What happened?

My luckyblock plugin doesn't work anymore with the new bw2023 beta build , when i break a luckyblock in a arena (because it work on my lobby), it only drop a sponge block , i retried with a older build and it worked

### Expected Behaviour

When i break a block choosen as a luckyblock (in my case , a sponge) , it give me a loot

### How to Reproduce

install lastest version of bw2023 + NewAmazingLuckyblocks ( https://www.spigotmc.org/resources/new-amazing-lucky-blocks.62644/ ) and try to break luckyblocks in a arena 

### Console Log

no log

### Errors

no log

**Comment by Xxyuri2005xX** [comment]
Hi, we can evalutate the support to that luckyblocks plugin, even if thats's better if is directly the LB developer to add the support.

**Comment by Xxyuri2005xX** [comment]
i was giving a look to the luckyblocks wiki and i found the world list function, you can try to use that feature to add the support. [worlds](https://github.com/I2000C/NewAmazingLuckyBlocks/wiki/Commands-and-permissions#alb-worlds)
this can be a temporary solution to the problem and, as i said in the message above, it's better if it's the developer to add the support to bw2023 instead of us.

**Comment by AIGLE25** [comment]
> i was giving a look to the luckyblocks wiki and i found the world list function, you can try to use that feature to add the support. [worlds](https://github.com/I2000C/NewAmazingLuckyBlocks/wiki/Commands-and-permissions#alb-worlds) this can be a temporary solution to the problem and, as i said in the message above, it's better if it's the developer to add the support to bw2023 instead of us.

already tested this so i will ask him to add support 
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/07628295-0dd9-49ba-8375-7310955c5c8d)

**Comment by tomkeuper** [comment]
This is not an issue with bedwars, we dont actively block luckyblocks. And without any information about how the addon works, we cannot help to solve this issue either
