### ISSUE TITLE
/bw start debug causes NPE

### ISSUE THREAD

**Issue by Lagggpixel** [tomkeuper/BedWars1058#249]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [X] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

An NPE was thrown when doing /bw start debug

### Expected Behaviour

N/A

### How to Reproduce

1. Go into a game
2. Do /bw start debug

### Console Log

https://pastebin.com/7WQQsjdQ

### Errors

https://pastebin.com/sWA4Ev7V

**Comment by tomkeuper** [comment]
Will be fixed in the next version. Just FYI your issue should have been closed since you didnt read the checklist properly :)
