### ISSUE TITLE
Molten Forge Max Upgrade (Hologram Bug)

### ISSUE THREAD

**Issue by Zsomi** [tomkeuper/BedWars1058#252]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

As soon as I upgraded the Molten Forge upgrade to the maximum, the emerald generator hologram appeared above the team generator.

### Expected Behaviour

Not Placeholderapi bug

### How to Reproduce

1. Open the Team upgrade.
2. Upgrade the Molten Forge upgrade (Max)
3. See the Team generator

### Console Log

https://pastebin.com/ndLGt4YR

### Errors

https://pastebin.com/XPZ6MahH

### Additional Info

Also, in the Team shop, if you buy a bedbug and a dream defender item and you look at it, it turns into a vanilla item that doesn't summon anything.

![image](https://github.com/tomkeuper/BedWars2023/assets/31018282/b9ee27ec-919a-4536-b797-9be5cc925ce7)
![image](https://github.com/tomkeuper/BedWars2023/assets/31018282/b370e787-9030-4dcd-9579-d02b8439d583)

**Comment by KKiiya** [comment]
This is my bad, apologies, i will fix it soon

**Comment by KKiiya** [comment]
Excluding the other errors, those are fixed afaik, if not, @tomkeuper will say if he has pushed changes or not

**Comment by Zsomi** [comment]
I downloaded the Bedwars2023 plugin from discord and detected these errors.

**Comment by KKiiya** [comment]
> I downloaded the Bedwars2023 plugin from discord and detected these errors.
> 

I know, those errors were already reported and known, but not fixed, thanks for reminding though

**Comment by Zsomi** [comment]
Ohh then I'm sorry I didn't know.

**Comment by tomkeuper** [comment]
The errors have been fixed yes. A new version is available on [discord](https://discord.com/channels/760851292826107926/1226891476928167977)

Let is know if you find any other errors!
