### ISSUE TITLE
checkWinner Method Null

### ISSUE THREAD

**Issue by ImYenil** [tomkeuper/BedWars1058#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 

**Additional context**
https://pastebin.com/KpAyExeW
https://pastebin.com/QJViHEuP

**Comment by tomkeuper** [comment]
Do you have the full server log? At least the part where the issue occurs?

**Comment by tomkeuper** [comment]
@porudev I added you here but I can take a look tonight if you want

**Comment by tomkeuper** [comment]
> > Do you have the full server log? At least the part where the issue occurs?
> 
> Only happens when bedwars game is end
Do you have a plugin list?

**Comment by porudev** [comment]
> > > Do you have the full server log? At least the part where the issue occurs?
> > > Only happens when bedwars game is end
> 
> Do you have a plugin list?

my ISP blocked pastebin can you send the thing to me

**Comment by tomkeuper** [comment]
Maybe still send the full server log, we need more info like joined players and game status

**Comment by ImYenil** [comment]
> > > > Do you have the full server log? At least the part where the issue occurs?
> > > > Only happens when bedwars game is end
> > 
> > 
> > Do you have a plugin list?
> 
> my ISP blocked pastebin can you send the thing to me

Only bedwars1058 plugin

**Comment by tomkeuper** [comment]
Let us know if this fixed in BETA2
