### ISSUE TITLE
FireBall Tnt Lagg

### ISSUE THREAD

**Issue by Zsomi** [tomkeuper/BedWars1058#264]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [X] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

Essentially, when I drop a fireball or TNT and it explodes, there is a delay in clearing the blocks around it and a delay in the sound.

### Expected Behaviour

My expectation was that if 3-5 fireballs or tnt exploded it would instantly remove the block around it. Not lagging.

### How to Reproduce

1. Join the Arena
2. Start the Arena
3. Buy a lot of Fireball and TnT
4. Throw fireballs and place tnts.

### Console Log

https://pastebin.com/U4qc1e5j

### Additional Info

I tested LighSpigot on server jaron and experienced the same lag.

If you throw more than one in a row, you get lag even with cooldown.

Spark Link:
https://spark.lucko.me/YSzcYuy5Yb

https://github.com/tomkeuper/BedWars2023/assets/31018282/d85eb2a0-0b98-4fa6-bee8-2959455dd3d9

**Comment by tomkeuper** [comment]
BlastProtection util has been removed since it surfed no real purpose. This should fix all lagg related issues
