### ISSUE TITLE
Set upgrade shop pricing per group

### ISSUE THREAD

**Issue by ImYenil** [tomkeuper/BedWars1058#27]
I would like to set the upgrade price per group. Is it possible to add?

**Comment by Xxyuri2005xX** [comment]
upgrade shop & generators already support per-group prices, was enough reading the wiki.

**Comment by ImYenil** [comment]
> upgrade shop & generators already support per-group prices, was enough reading the wiki.

I already read. but it doesn't work

**Comment by Xxyuri2005xX** [comment]
then they are to be fixed I think.
