### ISSUE TITLE
Kill stats don't get saved/update

### ISSUE THREAD

**Issue by porudev** [tomkeuper/BedWars1058#275]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

The plugin doesn't save/update regular kill stats

### Expected Behaviour

The plugin to update regular kill stats

### How to Reproduce

Just a normal BUNGEE setup should give you it with MySQL database

### Console Log

No provided log

### Errors

No provided error

### Additional Info

No extra info

**Comment by AIGLE25** [comment]
doesn't work for me on multiarena too
