### ISSUE TITLE
dragon does not generate

### ISSUE THREAD

**Issue by BaiPiaoCN** [tomkeuper/BedWars1058#287]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

My dragon don't spawn properly after all the events are over, either in the party or by default.

### Expected Behaviour

Normal Generation Dragon

### How to Reproduce

Wait for all events to end

**Comment by tomkeuper** [comment]
Ender dragons do spawn on my tests
