### ISSUE TITLE
Bug invisibility + inventory bug while invisible

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#288]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

https://youtu.be/uZfIIKv9d_4

### Expected Behaviour

The armor should become invisible , and the inventory should not bug 

### How to Reproduce

Get an invis from an other way than potion, and see

**Comment by AIGLE25** [comment]
i think i fixed the inventory part by removing this line but now idk how to make the armor invis 
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/8e4567fe-380e-4ffe-bdb1-613ff2584b85)

**Comment by tomkeuper** [comment]
How are you even able to take armor off since bw blocks any click even on your armor slots

**Comment by AIGLE25** [comment]
> How are you even able to take armor off since bw blocks any click even on your armor slots

i disabled it in the code

**Comment by tomkeuper** [comment]
What do you mean with in code?

**Comment by AIGLE25** [comment]
> What do you mean with in code?
this code
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/4905f219-24c5-4287-aa84-aa5e0664beba)

**Comment by tomkeuper** [comment]
So this is not an issue unless you change code right?

**Comment by AIGLE25** [comment]
> So this is not an issue unless you change code right?

the armor slot unlocked is not the bug , the bug was that it close my inventory automaticaly , so this is causing issue , but i mean, the bug now is the armor not getting invisible when i get invisibility by a other way than a potion

**Comment by tomkeuper** [comment]
Yeah but if I understand it correctly. the initial bug is caused by something you changed in the code. So if you want the armor slot to be unlocked we need to implement that as a feature correct?

**Comment by AIGLE25** [comment]
> Yeah but if I understand it correctly. the initial bug is caused by something you changed in the code. So if you want the armor slot to be unlocked we need to implement that as a feature correct?

i dont think its caused by my changes , but i can try with the legacy build

**Comment by AIGLE25** [comment]
the armor is still visible on the official build 
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/0f266d09-47ab-4327-8ea6-b0ec060a82cd)

and when i clicked on my armor while being invisible , the armor doesn't show anymore
![image](https://github.com/tomkeuper/BedWars2023/assets/68445450/d7b8647e-afc9-46d0-a403-79628686d13d)

**Comment by tomkeuper** [comment]
im not sure how to reproduce this bug. Can you tell me what changes you made to the config/server to produce this result?

**Comment by AIGLE25** [comment]
> im not sure how to reproduce this bug. Can you tell me what changes you made to the config/server to produce this result?

can you try /effect "player" 14 ?

**Comment by tomkeuper** [comment]
But the invis effect is something else than drinking the invis potion. Since then there is more logic to it than just applying the invis effect.

**Comment by AIGLE25** [comment]
> But the invis effect is something else than drinking the invis potion. Since then there is more logic to it than just applying the invis effect.

yeah but i think it's maybe why the armor isn't hided

**Comment by tomkeuper** [comment]
When you drink an invis potion it does hide the armor

**Comment by AIGLE25** [comment]
> When you drink an invis potion it does hide the armor

yeah it work , but if you use a throwable invis potion , it will not work

**Comment by tomkeuper** [comment]
Ahh I see, that would only work if we can register a listener to when potions are applied.

**Comment by AIGLE25** [comment]
> Ahh I see, that would only work if we can register a listener to when potions are applied.

so it will work if i use a wand  or a commad that apply invis effect to a player ?

**Comment by tomkeuper** [comment]
Not at the moment no, unless the plugin applying these effects will put the player in the correct invis list within bedwars. However maybe we can change that it will also work when an invis effect gets applied outside the bedwars plugin

**Comment by AIGLE25** [comment]
> Not at the moment no, unless the plugin applying these effects will put the player in the correct invis list within bedwars. However maybe we can change that it will also work when an invis effect gets applied outside the bedwars plugin

would be great

**Comment by tomkeuper** [comment]
The latest version has quite a lot of invisibility changes. Please let me know your findings!

**Comment by tomkeuper** [comment]
This issue is closed due to being stale. You can reopen this if needed or create a new issue.
