### ISSUE TITLE
hit delay issue and game breaking issue

### ISSUE THREAD

**Issue by AIGLE25** [tomkeuper/BedWars1058#291]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

When a player die from a harm potion and bows (or sometime by hands) , he will have no hit delay so he will be combo so easy

### Expected Behaviour

a normal fight with hit delay on 1.8.8

This is a video with a old bw2023 build (working) 
https://youtu.be/pcNkUe2c-o4

This is a video with bw1058 (working) (same server)
https://youtu.be/u98l8QemBa4

This is a video with a recent bw2023 build (not working) (same server)
https://youtu.be/hUmXJLd_ejs

This is a video of ticking player fatal error (same server)
https://youtu.be/Ted2opnM9Ic
https://pastebin.com/urBpPMGG

### How to Reproduce

get a harm potion , kill player with it , and fight him after respawn 

### Errors

https://pastebin.com/urBpPMGG

### Additional Info

windows 10 
1.8.8 papermc

**Comment by tomkeuper** [comment]
Is this issue completely fixed now?

**Comment by AIGLE25** [comment]
> Is this issue completely fixed now?

should be
