### ISSUE TITLE
Placeholder not working.

### ISSUE THREAD

**Issue by koalesanajlepsze** [tomkeuper/BedWars1058#292]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

The Placeholder for someone buying an upgrade isn't working.

### Expected Behaviour

That it would say the upgrade someone bought.

### How to Reproduce

1. Go to Upgrade Shop
2. Buy an upgrade
3. Look at chat.

### Additional Info

Screenshot: https://imgur.com/01PKIrB

**Comment by tomkeuper** [comment]
![image](https://github.com/tomkeuper/BedWars2023/assets/29728836/33a27278-4515-424c-8d79-f2c7417768c9)

**Comment by tomkeuper** [comment]
You probably messed up something with the config

**Comment by koalesanajlepsze** [comment]
what's your placeholder?

> You probably messed up something with the config

**Comment by tomkeuper** [comment]
`%bw_item%`

**Comment by koalesanajlepsze** [comment]
> `%bw_item%`

I dont understand how it is not working for me, I guess I will just delete the whole config file
