### ISSUE TITLE
First sword is always bugged.

### ISSUE THREAD

**Issue by koalesanajlepsze** [tomkeuper/BedWars1058#297]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

https://youtu.be/RV1dkA_Z9so?si=wD0Cqnq_kgECmm_E and when the game starts the wooden sword is breakable too.

### Expected Behaviour

Then first sword should be unbreakable and enchanted too.

### How to Reproduce

1. Start an arena
2. Buy sharpness upgrade
3. Buy a sword
4. It's always the first one that is bugged

### Additional Info

No errors.

**Comment by tomkeuper** [comment]
Regarding the swords being breakable did you set `is-unbreakable: true` in the shop config file?

**Comment by tomkeuper** [comment]
As I said on discord. I cant replicate these issues. Maybe try resetting your config files

**Comment by tomkeuper** [comment]
Issue was caused by an addon
