### ISSUE TITLE
Store holograms don't show up

### ISSUE THREAD

**Issue by BaiPiaoCN** [tomkeuper/BedWars1058#299]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

My store holograms don't show up in single combat.

### Expected Behaviour

Same hologram as 4v4v4v4 that shows the store overhead

### How to Reproduce

1. create tems
2.  Start game

**Comment by tomkeuper** [comment]
Missing information

**Comment by BaiPiaoCN** [comment]
What information do I need to provid-------- 原始邮件 --------发件人： MrCeasar ***@***.***>日期： 2024年6月30日周日 22:28收件人： tomkeuper/BedWars2023 ***@***.***>抄送： Mr_baipiaoCN ***@***.***>, Author ***@***.***>主    题： Re: [tomkeuper/BedWars2023] Store holograms don't show up (Issue #299)
Missing information

**Comment by tomkeuper** [comment]
Screenshots, Version, logs, anything that could help

**Comment by BaiPiaoCN** [comment]
I'm trying to use my mobile phone number: 16598674551
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 31
Device Name: HUAWEIGFY-AL00
Locale: zh

**Comment by tomkeuper** [comment]
What?
