### ISSUE TITLE
shops can be blown up

### ISSUE THREAD

**Issue by Shellyshellakano** [tomkeuper/BedWars1058#314]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

i can blow up the team shop and upgrade shop with a fire ball or tnt

### Expected Behaviour

team shop and upgrade shop connot be blown up

### How to Reproduce

get 40 iron buy a fire ball shoot at the shop keeper or upgrade shop or get a tnt and do the same as with the fire ball

### Console Log

https://pastebin.com/wQCh2rZw

### Additional Info

server software paper 1.20.4
os linux
java version 21
plugin version 1.2.0

**Comment by tomkeuper** [comment]
Probably caused by some other plugin. Shop keepers are protected from fireballs and explosions
