### ISSUE TITLE
Potion empty bottle

### ISSUE THREAD

**Issue by EhsanMNA** [tomkeuper/BedWars1058#315]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

After drinking potions, they empty bottles stay remaining!

### Expected Behaviour

it should not give empty potion bottle

### How to Reproduce

----

**Comment by tomkeuper** [comment]
Any proof? Server info?

**Comment by ritana5** [comment]
Well this happens to me also on 1.8.8 after you drink a potion you keep the empty bottle.

**Comment by George-Xeno** [comment]
I am currently using 1.20.1.After consuming the potion, an empty bottle will remain :(

**Comment by tomkeuper** [comment]
It has something to do with the logic of removing bottles from your inventory, but I think it only happens when you have multiple potions in your inventory

**Comment by tomkeuper** [comment]
This should be fixed now. Ill release an update soon!
