### ISSUE TITLE
Tested the plugin with 5 players, i'll write down a few mistakes now, and soon the rest

### ISSUE THREAD

**Issue by gaborazsdazds** [tomkeuper/BedWars1058#316]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

the magic milk:
- expires too soon, twice the time would be optimal.
potions:
- after drinking the potion, the empty bottle remains in the inventory. all three potions have this problem
invis potion:
- after the teammate's invis, the player disappears completely after a few seconds.
exploded blocks:
- exploded blocks do not get nbt tags, they are not stackable
arrow:
- the fired arrow does not accumulate when it is picked up, the fired arrow accumulates only with the fired arrow.
stone sword problem:
- if you have sharpness enchant and you buy a new stone sword, the sharpness will not be added
problem with player pushing:
- if you push a player on the opposing team, you do not get the ores he had
dragon:
- does not destroy, only tells you in bossbar which team you belong to
alarm trap:
- if you remove the invisibility effect, the opponent has no equipment

### Expected Behaviour

since it is hypixel style, it should work as on the hypixel server

### How to Reproduce

we just played against each other in several teams and experienced these problems

### Console Log

no error

### Errors

no error

### Additional Info

jar: flamepaper (premium spigot fork)
version: 1.8

**Comment by ritana5** [comment]
Would you mind testing something for me with the potions? I need you to go into the shop.yml and change all the data values of all the potions to 0. This will change them to a default color, but I need you to see if the empty bottles still remain after doing this.

**Comment by gaborazsdazds** [comment]
same problem, so I rewrote what you wrote

**Comment by EhsanMNA** [comment]
Same problems + Top killers display names sometimes is "NoBody"

**Comment by tomkeuper** [comment]
Todo:
- [x] Make magic milk configurable
- [x] Check exploded block NBT tags
- [x] Arrow NBT 
- [ ] ~~Sword sharpness check when buying a new sword~~
- [x] Dragon does not destroy blocks
- [x] No equipment for opposing team after invis
- [x] Teammate completely dissapears after a few seconds when invis

**Comment by tomkeuper** [comment]
The sword sharpness issue doesnt happen to me. I bought new swords and still got sharpness
![image](https://github.com/user-attachments/assets/b42372ad-0dd8-493a-9169-54d42d570675)

**Comment by gaborazsdazds** [comment]
I'll make a video of it in a few days when I'm on the plane if necessary.

**Comment by tomkeuper** [comment]
> I'll make a video of it in a few days when I'm on the plane if necessary.

Sure but it might also be a configuration issue on your end

**Comment by tomkeuper** [comment]
So far I have fixed all issues except for the sharpness thing you are talking about. I will close this issue but if you happen to run into it again please open a new issue!

**Comment by gaborazsdazds** [comment]
Okay, I'm waiting for the new jar release
