### ISSUE TITLE
teamkill with fireball and tnt

### ISSUE THREAD

**Issue by gaborazsdazds** [tomkeuper/BedWars1058#322]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

teammate can be killed using tnt and fireball
proofs:
pushing a teammate using tnt and fireball:
https://www.youtube.com/watch?v=qUz4qHtqkDc
tnt "instant" kill:
https://www.youtube.com/watch?v=cvwtbqhvr0Y

### Expected Behaviour

I think it's obvious

### How to Reproduce

above I have posted video links

**Comment by tomkeuper** [comment]
You can change this in the config.
