### ISSUE TITLE
fireball full random operation

### ISSUE THREAD

**Issue by gaborazsdazds** [tomkeuper/BedWars1058#323]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

fireball full random operation, the guy in the video uses the same technique throughout
video: https://www.youtube.com/watch?v=Kzzzi1C99c0

### Expected Behaviour

you should always throw to the same height with the same technique

### How to Reproduce

above I have posted video link

**Comment by tomkeuper** [comment]
Maybe dont throw a fireball at your teammate? This is all configurable in the config

**Comment by gaborazsdazds** [comment]
> Maybe dont throw a fireball at your teammate? This is all configurable in the config

Fireball settings in the video: https://imgur.com/Du8GpH6
