### ISSUE TITLE
interesting silverfish operation

### ISSUE THREAD

**Issue by gaborazsdazds** [tomkeuper/BedWars1058#324]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

sometimes not moving, sometimes too fast

### Expected Behaviour

should always move at the same speed

### How to Reproduce

https://www.youtube.com/watch?v=8iBeicGTyYc

**Comment by tomkeuper** [comment]
hit me up on discord so I can send you a beta build to test if it has been fixed

**Comment by tomkeuper** [comment]
As I mentioned in discord. you can change the speed of silverfish in the shop config. The attributes are fine now
