### ISSUE TITLE
golem problems

### ISSUE THREAD

**Issue by gaborazsdazds** [tomkeuper/BedWars1058#325]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

video1: golems have too much hp, they are too powerful. 
link: https://www.youtube.com/watch?v=RER8Zb_Z_HI
video2: golems attacking each other, even those from the same team
link: https://youtu.be/Rd62PmnY1CA

### Expected Behaviour

I think it's obvious

### How to Reproduce

above I have posted video links

**Comment by tomkeuper** [comment]
This issue has the same cause as #324 so I will close this one for now
