### ISSUE TITLE
Stone Sword Duplication Bug - Multiple Swords Can Be Purchased for Free

### ISSUE THREAD

**Issue by AlHadiHabib** [tomkeuper/BedWars1058#332]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

There is a bug allowing players to duplicate stone swords in the shop. After purchasing the first stone sword (which correctly deducts iron or currency), any additional stone swords can be purchased for free. This issue seems to be specific to stone swords, as other items are unaffected.

### Expected Behaviour

- Players should only be allowed to purchase one stone sword.
- The correct amount of iron or currency should be deducted for the first purchase, and no additional stone swords should be available for purchase.

### How to Reproduce

- Purchase a stone sword (iron or currency is deducted).
- Try to purchase another stone sword.
- Observe that no currency is deducted for the second (and subsequent) swords.

### Console Log

https://mclo.gs/H8qS9J4

### Errors

https://mclo.gs/H8qS9J4

### Additional Info

Mode: Proxy/Bungee
Server: CarbonSpigot
BW2023 Version: Latest from github release.
Plugins (23): PrivateGames, FallDamageModifier, SlimeWorldManager, PlaceholderAPI, spark, FastAsyncWorldEdit, IPWhitelist, ViaVersion, LuckPerms, WorldEdit, ProtocolLib, Citizens, BungeeGuard, AdvancedPlHide, packetevents, TAB, KarhuLoader, BedWars2023, BedWars-SpectatorOptions, BedWars1058-AdventureMode, XpBar, BedWars1058-Compass, BedWars2023-TeamSelector

**Comment by tomkeuper** [comment]
Can this be caused by one of your addons?

**Comment by AlHadiHabib** [comment]
Definitely no way, because I have tried disabling every single plugin and addon one by one. I also tried multiple client versions.

**Comment by AlHadiHabib** [comment]
The issue was caused by a language file configuration and has been resolved.
