### ISSUE TITLE
 Leave delay not working – Players sent directly to BW lobby after clicking bed in pre-lobby

### ISSUE THREAD

**Issue by AlHadiHabib** [tomkeuper/BedWars1058#333]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

When players click the bed item in the pre-lobby, they are immediately sent to the BedWars (BW) lobby, bypassing the intended leave delay. I have configured the `/bw leave delayed` command to be triggered by the pre-lobby bed item, but it appears that the leave delay is not functioning as expected.

### Expected Behaviour

Players should experience a delay after clicking the bed, rather than being sent directly to the BW lobby.

### How to Reproduce

- Set /bw leave delayed command to the pre-lobby bed item.
- Enter the pre-lobby.
- Click the bed item.

### Console Log

https://mclo.gs/WmPpIqQ

### Errors

https://mclo.gs/WmPpIqQ

### Additional Info

Mode: Proxy/Bungee
Server: CarbonSpigot
BW2023 Version: Latest from github release.
Plugins (23): PrivateGames, FallDamageModifier, SlimeWorldManager, PlaceholderAPI, spark, FastAsyncWorldEdit, IPWhitelist, ViaVersion, LuckPerms, WorldEdit, ProtocolLib, Citizens, BungeeGuard, AdvancedPlHide, packetevents, TAB, KarhuLoader, BedWars2023, BedWars-SpectatorOptions, BedWars1058-AdventureMode, XpBar, BedWars1058-Compass, BedWars2023-TeamSelector

**Comment by tomkeuper** [comment]
Leave delay has been changed. You need to add "leave-delay: x" to the item you want to have a leave delay

```yml
pre-game-items:
  stats:
    material: SKULL_ITEM
    data: 3
    enchanted: false
    slot: 0
  leave:
    material: BED
    leave-delay: 3
    data: 0
    enchanted: false
    slot: 8
```
