### ISSUE TITLE
Placeholder %bw_on% and %bw_max% Not Displaying Correctly for Player Leave Messages

### ISSUE THREAD

**Issue by AlHadiHabib** [tomkeuper/BedWars1058#334]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

I am using the placeholders %bw_on% and %bw_max% to display player counts in join and leave messages during a match or in the pre-lobby. While the placeholders work perfectly for the join message, they do not function correctly for the player leave message. Instead of outputting the actual numbers, they return the placeholder itself.

### Expected Behaviour

`%bw_on% and %bw_max%` should display the correct player count in both join and leave messages.

### How to Reproduce

You already know how to do.

### Console Log

https://mclo.gs/peuwALs

### Errors

https://mclo.gs/peuwALs

### Additional Info

Mode: Proxy/Bungee
Server: CarbonSpigot
BW2023 Version: Latest from github release.
Plugins (23): PrivateGames, FallDamageModifier, SlimeWorldManager, PlaceholderAPI, spark, FastAsyncWorldEdit, IPWhitelist, ViaVersion, LuckPerms, WorldEdit, ProtocolLib, Citizens, BungeeGuard, AdvancedPlHide, packetevents, TAB, KarhuLoader, BedWars2023, BedWars-SpectatorOptions, BedWars1058-AdventureMode, XpBar, BedWars1058-Compass, BedWars2023-TeamSelector

Config: Language config file attached. 
[messages_en.zip](https://github.com/user-attachments/files/17370936/messages_en.zip)

Image: 
![image](https://github.com/user-attachments/assets/12b2ed97-3fd2-4403-994c-cb5e8ea6034d)

**Comment by tomkeuper** [comment]
Will be fixed in the next release!
