### ISSUE TITLE
Colour problems (3 team)

### ISSUE THREAD

**Issue by G6bor** [tomkeuper/BedWars1058#339]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

3 teams with some problems. The pictures show perfectly what the problem is.  Example: darkblue team wrong armour colour and etc. Each character stands in front of its own colour.
![2024-12-03_22 17 33](https://github.com/user-attachments/assets/1edab8d1-0234-4c54-ba9e-ad8a6011b927)
![2024-12-03_22 18 05](https://github.com/user-attachments/assets/20427e90-abfe-4cd0-9c2a-ff7abe143227)
![2024-12-03_22 18 18](https://github.com/user-attachments/assets/5ba56ac0-5066-40f4-95ea-27503398a8e2)

### Expected Behaviour

Team colours should include good colours.

### How to Reproduce

I used these colours when installing Arena.

### Additional Info

1.3.0 plugin release and 1.8 server version

**Comment by KKiiya** [comment]
Even if I understood what the problem seems to be, the way you described the problem shouldn't be the way to do it. Please next time keep in mind that we need a description regarding bugs or issues. I'll assign this myself and fix it. Thanks for the report.

**Comment by ritana5** [comment]
I think there should potentially be a way to configure all the color elements of team colors, and possibly create our own without editing code.

**Comment by KKiiya** [comment]
There's no way to create your own since the colors for some things are limited to bukkit default color

**Comment by ritana5** [comment]
I meant things like armor color, and changing things between the team color
name or small things like aqua or light blue wool.

**Comment by ritana5** [comment]
Also would it be possible to integrate the hex colors that are supported 1.16+?

**Comment by KKiiya** [comment]
Fixed, check #342
