### ISSUE TITLE
Database Improvements

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#40]
**Is your feature request related to a problem? Please describe.**
Is your feature request related to a problem? Please describe.
BedWars1058 actually supports 2 types of databases (SQLite and MySQL).

**Describe the solution you'd like**
- Implement a database API with methods like initialization, stopping, saving stats, etc (could be an idea moving the Database.class from bedwars-plugin to bedwars-api) and implement new database types for saving stats/shops (especially NoSQL databases like MongoDB).
- Implement a method `BedWars#setDatabaseAdapter(IDatabase database)`

**Additional context**

**Comment by Diamondy01** [comment]
I think replacing SQlite with h2, would be a good step forward, it just has better performance

**Comment by Xxyuri2005xX** [comment]
> I think replacing SQlite with h2, would be a good step forward, it just has better performance

Wanting could also implement H2 as an available option, perhaps integrated into bw2023 but without making it a replacement for SQLite but a possibility that can be activated via config

**Comment by tomkeuper** [comment]
Whats the benefit of implementing both?

**Comment by Xxyuri2005xX** [comment]
or if you want we can migrate to just H2 as local DB system but weneed a system to migrate shop, stats, levels, language and any other parameters to H2 system

**Comment by tomkeuper** [comment]
I'll close this issue since the main topic is completed.
Do we need a seperate issue for the convertion? (Maybe it doesnt need to be just stats we can maybe also do something to migrate from bw1058 to bw2023)
