### ISSUE TITLE
RGB support

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#43]
**Is your feature request related to a problem? Please describe.**
Since the 1.16 version Minecraft has implemented the possibility to use RGB codes in messages, actually BedWars1058 not supports this feature.

**Describe the solution you'd like**
Implementing a config option like **rgb/hex-enable:true/false** and adding RGB support (mabye by using some libraries like IridiumColorAPI)

**Describe alternatives you've considered**

**Additional context**

**Comment by tomkeuper** [comment]
Closing as implemented in #45
