### ISSUE TITLE
elapsed time placeholder bug

### ISSUE THREAD

**Issue by Xxyuri2005xX** [tomkeuper/BedWars1058#46]
**Describe the bug**
When 60 seconds pass with the %bw1058_elapsed_time% placeholder the minute gets added but the seconds don't get resetted

**To Reproduce**
1: Add elapsed time placeholder in sidebar or tab
2: wait 60 seconds
3: bug appears

**Screenshots**
![bug](https://user-images.githubusercontent.com/84080587/230781729-9e347aee-224d-488e-827e-b9368363c144.PNG)

**System (please complete the following information):**
 - OS: 
 - Server software NachoSpigot
 - Server Version 1.8.8
 - Plugin Version latest

**Comment by Xxyuri2005xX** [comment]
Closed as implemented fix.

**Comment by tomkeuper** [comment]
quite sus that the pr didnt close this

**Comment by Xxyuri2005xX** [comment]
a bit
