### ISSUE TITLE
Game start shortend gets ignored

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#50]
**Describe the bug**
Default shortend time in config is 10 seconds but in game its 5 seconds.

**To Reproduce**
use /bw start

**Expected behavior**
10 seconds countdown.

**Comment by ImYenil** [comment]
Fixed https://github.com/tomkeuper/BedWars1058/pull/55

**Comment by tomkeuper** [comment]
Closing as fixed with PR
