### ISSUE TITLE
Can buy item when no inventory space

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#53]
**Describe the bug**
When your inventory is full you can buy items from the shop, this will take the cost out of your inventory but it will not give you the item.

**To Reproduce**
Inv full > buy item from shop

**Comment by ImYenil** [comment]
Fixed https://github.com/tomkeuper/BedWars1058/pull/56

**Comment by tomkeuper** [comment]
Fixed with 6e76033bed977f1251a666e3aa56890fc1797f72

**Comment by tomkeuper** [comment]
Closing as fixed
