### ISSUE TITLE
PerMinuteTask throws an error during gameplay

### ISSUE THREAD

**Issue by ImYenil** [tomkeuper/BedWars1058#54]
**Describe the bug**
PerMinuteTask throws an error during gameplay

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS:  windows
 - Server software  paper
 - Server Version  1.8.8
 - Plugin Version  23.3

**Additional context**
https://pastebin.com/FtvwL0SP

**Comment by tomkeuper** [comment]
Are you using a custom version?

**Comment by ImYenil** [comment]
> Are you using a custom version?

Yes

**Comment by tomkeuper** [comment]
Did you happen to change something regarding the perMinuteTask?
And you should send the whole error / whole console log

**Comment by tomkeuper** [comment]
But I cannot try and figure out whats going on if you are running a custom version. Just so you know

**Comment by ImYenil** [comment]
> Did you happen to change something regarding the perMinuteTask? And you should send the whole error / whole console log

i didn't change this part

**Comment by ImYenil** [comment]
> But I cannot try and figure out whats going on if you are running a custom version. Just so you know

I am using a custom version I made

**Comment by tomkeuper** [comment]
If thats the case you can post questions in the discord as long as you provide some good info. With just an error there is not much we can do. This github is only for issues with code thats in this specific repo. 

So if you have a question about your changes make sure to use discord.
