### ISSUE TITLE
water can be placed above build limit

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#60]
**Describe the bug**
A water bucket can be emptied on top of the build limit blocks. This way you are also not able to remove the source block

**To Reproduce**

**Expected behavior**
No water above build height

**Screenshots**
![image](https://user-images.githubusercontent.com/29728836/233015799-31049378-ec09-4c02-b121-fcd54b618450.png)

**Comment by porudev** [comment]
Fixed 258803066c35e66251ca3b1b5c541f8c4352f195
