### ISSUE TITLE
PopUp towers go above build limit

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#61]
**Describe the bug**
Placing a popup tower right under the build limit will cause it spawn partly above the build limit.
Someone also mentioned this was  the case with bridge eggs but I havent been able to reproduce this error

**Screenshots**
Note: limit is set at 180
![image](https://user-images.githubusercontent.com/29728836/233076406-01bde634-1c7b-4f9d-aa6f-183bae05283f.png)

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 

**Additional context**

**Comment by ImYenil** [comment]
Fix https://github.com/tomkeuper/BedWars1058/pull/62

**Comment by tomkeuper** [comment]
Closing as fixed with PR
