### ISSUE TITLE
Can buy items in your inventory instead of the shop that you open and should buy from there

### ISSUE THREAD

**Issue by KKiiya** [tomkeuper/BedWars1058#67]
**Describe the bug**
When you click in your side of your inventory in the villager shop it will detect it as if you were clicking in the shop

**To Reproduce**
1. Open the quick buy (or any submenu in the quickbuy)
2. Click in your inventory side

**Expected behavior**
Items only buyable in the inventory that the items are in

(Not sure if this is understandable)

**Comment by tomkeuper** [comment]
Do you have a screenshot or video? 
I'm not sure if I understand correctly

**Comment by KKiiya** [comment]
Of course, here it goes

https://user-images.githubusercontent.com/105589176/233206127-4c0c9d68-cb08-4afb-a0a8-37afb726c6d9.mp4

**Comment by ImYenil** [comment]
> Of course, here it goes
> 
>  javaw_20230419_233612F.mp4

This didn't happen to me. Did you edit anything?

**Comment by KKiiya** [comment]
> > Of course, here it goes
> > javaw_20230419_233612F.mp4
> 
> This didn't happen to me. Did you edit anything?

nope

**Comment by tomkeuper** [comment]
What client version is this and do you have a server log?

**Comment by porudev** [comment]
This is wrongly inputted by the client side, this isn't the behavior of a server side thing

**Comment by tomkeuper** [comment]
HAve you tried with a 100% vanilla client?

**Comment by Chromaah** [comment]
LOL WTF thats cursed

**Comment by tomkeuper** [comment]
@KKiiya is it fixed with vanilla client?

**Comment by KKiiya** [comment]
> @KKiiya is it fixed with vanilla client?

Sorry, i havent tested it yet, im having problems with my pc

**Comment by Squesly** [comment]
OK Its happens to me to
I'm on Badlion Client so Its not from Client side!

**Comment by tomkeuper** [comment]
Badlion client is also not vanilla tho. Does this issue happen all the time or?

**Comment by porudev** [comment]
I think i kind of know what causing this, let me know if it still present

**Comment by tomkeuper** [comment]
How about you say what you might think is causing this :)

**Comment by tomkeuper** [comment]
Any updates?

**Comment by Diamondy01** [comment]
I'll test this again and will update if this happens

**Comment by tomkeuper** [comment]
bump

**Comment by tomkeuper** [comment]
Please reopen with more info if this happens again. I dont seem to be able to reproduce it so we will need some clear steps on how to test this with the least amount of variables
