### ISSUE TITLE
When the build session is enabled, the block can be destroyed but cannot be placed.

### ISSUE THREAD

**Issue by ImYenil** [tomkeuper/BedWars1058#92]
**Describe the bug**

**To Reproduce**

**Screenshots**
https://user-images.githubusercontent.com/85287520/236636578-55a3e58b-d9a9-4707-b83c-724e62d70b12.mp4

**System (please complete the following information):**
 - OS:  Windows
 - Server software  paper
 - Server Version  1.8.8
 - Plugin Version  23.3-SPAPSHOT

**Comment by ImYenil** [comment]
solved

**Comment by tomkeuper** [comment]
what solved it?

**Comment by ImYenil** [comment]
> what solved it?

It was my mistake.
